

CLASSES = [
    'food trucks',
    'wolves',
    'tractors',
    'monkeys',
    'lavender',
    'plier',
    'nightstands',
    'citrus',
    'sporting equipment',
    'castles',
    'pikachu',
    'mice',
    'televisions',
    'dvd players',
    'fire trucks',
    'snakes',
    'panda bears',
    'eagles',
    'printers',
    'ravioli',
    'bread loaf',
    'rhinos',
    'pigs',
    'cooking oil',
    'snoopy',
    'hippos',
    'parrots',
    'waffles',
    'kittens',
    'parachutes',
    'sharks',
    'serving dish',
    'soccer balls',
    'farmers',
    'vitamins',
    'beer mug',
    'snail',
    'pandas',
    'lilies',
    'orchids',
    'mattresses',
    'bugs',
    'dinosaurs',
    'blenders',
    'pretzels',
    'dolphins',
    'dragons',
    'hamburgers',
    'penguins',
    'antelopes',
    'kangaroo',
    'pizza shop',
    'xbox controller',
    'owls',
    'supermarket',
    'entree',
    'swans',
    'taxis',
    'stuffed bears',
    'guests',
    'pudding',
    'boar',
    'lunch box',
    'donkeys',
    'hibiscus',
    'leopard',
    'dragonfly',
    'wok',
    'cappuccino',
    'mexican food',
    'juice box',
    'nutella',
    'wii controllers',
    'restaurants',
    'performer',
    'egg carton',
    'pistachio',
    'salon',
    'ice-cream cone',
    'lab coat',
    'kiwis',
    'wardrobe',
    'gourd',
    'french toast',
    'ladles',
    'sugar packet',
    'ginger',
    'croissants',
    'smoothie',
    'ostriches',
    'coconuts',
    'vinegar',
    'oatmeal',
    'coffee shop',
    'masks',
    'biscuits',
    'pizza boxes',
    'pita',
    'hummus',
    'kimono',
    'lions',
    'turbines',
    'amusement park',
    'snow shoe',
    'swamp',
    'coral',
    'beetle',
    'vanilla',
    'weapon',
    'fudge',
    'couches',
    'oreo',
    'egg white',
    'cafeteria',
    'attic',
    'pub',
    'artichokes',
    'armor',
    'appetizers',
    'buffet',
    'pizza pie',
    'soap dispensers',
    'granola',
    'anchovies',
    'food container',
    'dog food',
    'mint',
    'waitress',
    'gifts',
    'school',
    'whale',
    'cookbook',
    'farmer',
    'taco',
    'robot',
    'cemetery',
    'cake pan',
    'cheeseburger',
    'soft drink',
    'shopping center',
    'bird house',
    'ovens',
    'menus',
    'egg roll',
    'riding boots',
    'groceries',
    'roast beef',
    'gym',
    'poodle',
    'office supplies',
    'hairbrush',
    'baseball bats',
    'theater',
    'lobby',
    'bar stools',
    'chicken breast',
    'potato salad',
    'hand dryer',
    'orchard',
    'wines',
    'lizard',
    'elmo',
    'life jackets',
    'coffee beans',
    'wolf',
    'beer cans',
    'gorilla',
    'stir fry',
    'son',
    'pizza oven',
    'caramel',
    'visitors',
    'pills',
    'moose',
    'customers',
    'waiter',
    'walnuts',
    'cinnamon',
    'utensil holder',
    'pesto',
    'casserole',
    'meats',
    'towel dispenser',
    'watermelons',
    'bee',
    'lily',
    'vendors',
    'chocolate chips',
    'cookie jar',
    'chickens',
    'cookie dough',
    'chickpeas',
    'sweet potatoes',
    'cotton dessert',
    'gummy bear',
    'baked good',
    'picnic',
    'policemen',
    'shuttle',
    'mannequins',
    'napkin dispenser',
    'cake stand',
    'orchid',
    'melons',
    'bomb',
    'crab',
    'fisherman',
    'cheetah',
    'shoppers',
    'coffee cups',
    'snow flakes',
    'rifle',
    'shaving cream',
    'lemonade',
    'batteries',
    'cotton candy',
    'angry bird',
    'flatbread',
    'swimmer',
    'monster',
    'pork',
    'hotdog bun',
    'gadget',
    'beets',
    'action figure',
    'avocados',
    'popcorn',
    'dolls',
    'banana bunches',
    'bartender',
    'stew',
    'keyboards',
    'snow shoes',
    'champagne',
    'milkshake',
    'pasta salad',
    'cooking utensil',
    'rice cooker',
    'wedding',
    'palace',
    'chess piece',
    'soldiers',
    'blackberries',
    'wii game',
    'picnic tables',
    'cages',
    'outfits',
    'dream catcher',
    'lounge',
    'trumpet',
    'ice cube',
    'appetizer',
    'bread box',
    'pecan',
    'hospital',
    'pocket watch',
    'peacock',
    'food processor',
    'dry-erase board',
    'turtle',
    'sticky notes',
    'baker',
    'daughter',
    'cranberries',
    'pumpkins',
    'parmesan cheese',
    'seafood',
    'baking pan',
    'auditorium',
    'shopper',
    'dumplings',
    'artichoke',
    'pizza slices',
    'dish drainer',
    'pizza tray',
    'desktop computer',
    'officers',
    'pantry',
    'tuna',
    'bakery',
    'loaf',
    'paint brush',
    'piercing',
    'spray can',
    'squirrel',
    'meatballs',
    'can opener',
    'camel',
    'backpacks',
    'toolbox',
    'visitor',
    'onion rings',
    'ear buds',
    'cream cheese',
    'paper dispenser',
    'accessory',
    'mustard bottle',
    'kitchen towel',
    'almond',
    'tourists',
    'hippo',
    'snake',
    'ramekin',
    'thermometer',
    'dresses',
    'soda cans',
    'lambs',
    'paper container',
    'pizza pan',
    'eiffel tower',
    'mixing bowl',
    'burrito',
    'pliers',
    'mickey mouse',
    'panda bear',
    'cinnamon roll',
    'salad dressing',
    'scooters',
    'octopus',
    'hair clip',
    'cooking pot',
    'cat food',
    'cereal box',
    'alien',
    'snowboards',
    'toothpicks',
    'sweet potato',
    'shopping cart',
    'chef hat',
    'baked goods',
    'baking sheet',
    'factory',
    'microwave oven',
    'lobster',
    'spider',
    'hard drive',
    'vendor',
    'ice cubes',
    'liquor',
    'vacuum',
    'cigar',
    'waffle',
    'muffins',
    'ingredient',
    'cranberry',
    'egg shell',
    'beer can',
    'marshmallow',
    'students',
    'parent',
    'scrub brush',
    'egg yolk',
    'olive oil',
    'rolling pin',
    'broth',
    'sour cream',
    'grater',
    'rhino',
    'elevator',
    'necklaces',
    'mangoes',
    'cigarettes',
    'guacamole',
    'beverages',
    'mayonnaise',
    'library',
    'cheesecake',
    'horse hoof',
    'pretzel',
    'bell tower',
    'ice maker',
    'skateboards',
    'walnut',
    'oak tree',
    'mall',
    'cathedral',
    'beds',
    'temple',
    'whisk',
    'spear',
    'brownies',
    'butterflies',
    'bison',
    'sunflowers',
    'coleslaw',
    'rubber duck',
    'sugar packets',
    'remote controls',
    'salmon',
    'milk carton',
    'wig',
    'omelette',
    'desserts',
    'grinder',
    'peanuts',
    'almonds',
    'raisins',
    'dolphin',
    'rabbit',
    'peanut',
    'hammer',
    'coffee bean',
    'plantains',
    'water bottles',
    'beet',
    'mountain side',
    'shampoo bottle',
    'lego',
    'gift',
    'nest',
    'shark',
    'stuffed dog',
    'vests',
    'geese',
    'merchandise',
    'mountain peak',
    'rackets',
    'engineer',
    'wildflower',
    'sausages',
    'bird cage',
    'onion ring',
    'papaya',
    'seat belt',
    'phones',
    'cheese cube',
    'obstacle',
    'raspberries',
    'skyscrapers',
    'hand soap',
    'father',
    'potato chips',
    'bookshelves',
    'feta cheese',
    'hurdle',
    'packages',
    'alligator',
    'pomegranate',
    'toothbrushes',
    'classroom',
    'frog',
    'cameras',
    'toy car',
    'football',
    'tofu',
    'fishing pole',
    'bug',
    'chinese food',
    'storage box',
    'pig',
    'ambulance',
    'diaper',
    'sailboats',
    'snow boots',
    'snacks',
    'sconce',
    'games',
    'seagulls',
    'gas pump',
    'mugs',
    'tiger',
    'grapefruit',
    'helicopter',
    'sushi',
    'donkey',
    'video games',
    'dish soap',
    'earphones',
    'cherries',
    'mashed potatoes',
    'vending machine',
    'parrot',
    'pizza box',
    'museum',
    'router',
    'gown',
    'medicine cabinet',
    'aquarium',
    'peanut butter',
    'waste basket',
    'pancakes',
    'instrument',
    'restroom',
    'washing machine',
    'cash register',
    'underwear',
    'cakes',
    'backyard',
    'computer desk',
    'cell phones',
    'crackers',
    'hair dryer',
    'pineapples',
    'fruit stand',
    'snack',
    'chopstick',
    'garment',
    'bagels',
    'skillet',
    'student',
    'ostrich',
    'calculator',
    'jewelry',
    'monitors',
    'cracker',
    'honey',
    'soap bottle',
    'alcohol',
    'hangar',
    'shoe laces',
    'buns',
    'bats',
    'stores',
    'ribs',
    'penguin',
    'village',
    'brownie',
    'figurines',
    'tennis balls',
    'shops',
    'raisin',
    'shampoo',
    'raspberry',
    'bunny',
    'christmas light',
    'owl',
    'coin',
    'employee',
    'seal',
    'gentleman',
    'christmas lights',
    'electric toothbrush',
    'soccer player',
    'eagle',
    'customer',
    'workers',
    'blossoms',
    'macaroni',
    'banana peel',
    'yogurt',
    'food truck',
    'battery',
    'candies',
    'bath towel',
    'kiosk',
    'pizza cutter',
    'video camera',
    'serving tray',
    'toaster oven',
    'cafe',
    'mango',
    'ornaments',
    'school bus',
    'beach umbrella',
    'goats',
    'waterfall',
    'raincoat',
    'blossom',
    'knife block',
    'peaches',
    'suits',
    'sword',
    'pizzas',
    'pencils',
    'marina',
    'money',
    'laptops',
    'chalkboard',
    'antennas',
    'spray bottle',
    'cats',
    'turkey',
    'tortilla',
    'hotel room',
    'cooking utensils',
    'projector',
    'coconut',
    'tattoos',
    'ketchup bottle',
    'puppy',
    'panda',
    'teddy bears',
    'canisters',
    'bedding',
    'receipt',
    'pouch',
    'wheelchair',
    'dragon',
    'bottle cap',
    'desk lamp',
    'dining room',
    'eggplant',
    'stapler',
    'chili',
    'paintings',
    'hilltop',
    'flames',
    'pigeons',
    'sunflower',
    'cowboy',
    'desert',
    'tea pot',
    'athlete',
    'tourist',
    'hamburger',
    'pizza crust',
    'ladle',
    'luggage cart',
    'croissant',
    'soda bottle',
    'gas stove',
    'courtyard',
    'touchpad',
    'bandage',
    'uniforms',
    'cards',
    'toddler',
    'bar stool',
    'baseball mitt',
    'cds',
    'cooker',
    'biscuit',
    'comb',
    'farm',
    'buoys',
    'office chair',
    'coats',
    'bus driver',
    'meadow',
    'dinosaur',
    'baseball players',
    'bone',
    'blueberries',
    'table lamp',
    'parachute',
    'daisy',
    'hot dogs',
    'dining table',
    'sea foam',
    'soldier',
    'sandwiches',
    'trays',
    'pears',
    'pillowcase',
    'steak',
    'shower door',
    'suitcases',
    'lunch',
    'plain',
    'notepad',
    'drum',
    'hearts',
    'kitten',
    'apartment',
    'drawings',
    'coach',
    'pajamas',
    'blood',
    'breakfast',
    'turbine',
    'goose',
    'dip',
    'carts',
    'heels',
    'jackets',
    'computers',
    'wine bottles',
    'cabinet doors',
    'zucchini',
    'dinner',
    'mixer',
    'guys',
    'gas station',
    'keypad',
    'console',
    'cloths',
    'tractor',
    'melon',
    'sunglasses',
    'characters',
    'antelope',
    'envelope',
    'pickles',
    'broom',
    'fire truck',
    'lion',
    'jumpsuit',
    'toilet brush',
    'tissue box',
    'garlic',
    'water glass',
    'outlets',
    'stuffed animals',
    'dryer',
    'blankets',
    'dressing',
    'baskets',
    'whipped cream',
    'forks',
    'tablet',
    'pancake',
    'spoons',
    'cucumbers',
    'control panel',
    'chef',
    'cupboards',
    'light bulbs',
    'tents',
    'syrup',
    'price tag',
    'wine glasses',
    'rooftop',
    'kiwi',
    'pump',
    'life preserver',
    'homes',
    'armchair',
    'apartment building',
    'tea kettle',
    'polar bear',
    'gun',
    'ducks',
    'burger',
    'piano',
    'jockey',
    'trash bag',
    'video game',
    'terminal',
    'tea',
    'bagel',
    'dvd player',
    'trucks',
    'tangerine',
    'asparagus',
    'castle',
    'tv stand',
    'monkey',
    'drape',
    'tools',
    'sponge',
    'alarm clock',
    'crates',
    'beef',
    'scaffolding',
    'towers',
    'flour',
    'swan',
    'deer',
    'coffee pot',
    'dumpster',
    'gravy',
    'cane',
    'jars',
    'pans',
    'herb',
    'parsley',
    'skater',
    'ipod',
    'packet',
    'butter knife',
    'worker',
    'flamingo',
    'charger',
    'powder',
    'tissues',
    'mother',
    'cereal',
    'pie',
    'pastries',
    'hotel',
    'entertainment center',
    'soda can',
    'banana bunch',
    'goal',
    'coke',
    'drinks',
    'heater',
    'lipstick',
    'wildflowers',
    'parking sign',
    'herbs',
    'surfboards',
    'toiletries',
    'speakers',
    'muffin',
    'cactus',
    'moon',
    'closet',
    'vine',
    'radio',
    'cyclist',
    'oven door',
    'sack',
    'photographer',
    'minivan',
    'oil',
    'wallet',
    'mannequin',
    'helmets',
    'peas',
    'boulders',
    'fire',
    'trains',
    'lemons',
    'shield',
    'cupcakes',
    'dvds',
    'shopping bag',
    'clock hand',
    'beach chair',
    'feeder',
    'window frame',
    'butterfly',
    'tongs',
    'glaze',
    'lime',
    'floor lamp',
    'avocado',
    'safety jacket',
    'garnish',
    'stage',
    'cookies',
    'hedges',
    'apple logo',
    'team',
    'peach',
    'fire extinguisher',
    'pear',
    'elbow pad',
    'mozzarella',
    'fog',
    'dogs',
    'tags',
    'game controller',
    'balloons',
    'paper towel',
    'athletic shoe',
    'satellite dish',
    'toothpaste',
    'vases',
    'ice cream',
    'wagon',
    'salt',
    'toast',
    'bracelets',
    'soap dish',
    'beer bottle',
    'chopsticks',
    'toilet lid',
    'smoke stack',
    'pea',
    'girls',
    'clocks',
    'dress shirt',
    'officer',
    'dough',
    'briefcase',
    'tool',
    'leggings',
    'pepper shaker',
    'harbor',
    'binder',
    'pens',
    'side table',
    'blazer',
    'garland',
    'buses',
    'appliance',
    'nuts',
    'garage door',
    'soap dispenser',
    'roadside',
    'name tag',
    'town',
    'undershirt',
    'hallway',
    'powdered sugar',
    'sign post',
    'shrimp',
    'ropes',
    'bears',
    'chains',
    'toys',
    'toilet tank',
    'door frame',
    'crown',
    'polo shirt',
    'produce',
    'robe',
    'cans',
    'face mask',
    'fountain',
    'jeep',
    'match',
    'lighthouse',
    'celery',
    'roses',
    'printer',
    'squash',
    'herd',
    'cauliflower',
    'pizza slice',
    'pencil',
    'shelter',
    'pockets',
    'candle holder',
    'office',
    'tree leaves',
    'pilot',
    'vines',
    'minute hand',
    'pedestrians',
    'canister',
    'manhole cover',
    'mirrors',
    'earrings',
    'costume',
    'watermelon',
    'blueberry',
    'cowboy hat',
    'mailbox',
    'magazines',
    'knee pads',
    'beads',
    'calf',
    'heel',
    'map',
    'folding chair',
    'drapes',
    'market',
    'mattress',
    'roadway',
    'berries',
    'knives',
    'cd',
    'cabbage',
    'bubble',
    'radiator',
    'hats',
    'ottoman',
    'hour hand',
    'berry',
    'controllers',
    'snow pants',
    'balls',
    'shower curtain',
    'paper towels',
    'cigarette',
    'aircraft',
    'bubbles',
    'pasta',
    'ceiling light',
    'flip flop',
    'salt shaker',
    'picnic table',
    'platter',
    'shoe lace',
    'wii',
    'meal',
    'end table',
    'guitar',
    'cherry',
    'pineapple',
    'steam',
    'highway',
    'package',
    'garden',
    'bouquet',
    'audience',
    'blind',
    'tables',
    'notebook',
    'boys',
    'biker',
    'seed',
    'sugar',
    'rain',
    'railroad',
    'beverage',
    'tomato sauce',
    'lamps',
    'stadium',
    'life jacket',
    'magnets',
    'seaweed',
    'noodles',
    'bikini',
    'cliff',
    'flip flops',
    'coffee mug',
    'swimming pool',
    'ornament',
    'toaster',
    'butter',
    'foil',
    'tunnel',
    'soccer ball',
    'stump',
    'milk',
    'seagull',
    'wallpaper',
    'seeds',
    'twigs',
    'picture frame',
    'chandelier',
    'canoe',
    'bowls',
    'patio',
    'family',
    'nut',
    'coffee maker',
    'soup',
    'bookcase',
    'mushrooms',
    'bull',
    'character',
    'spatula',
    'airplanes',
    'handbag',
    'skyscraper',
    'swimsuit',
    'pasture',
    'garage',
    'air conditioner',
    'sea',
    'knee pad',
    'strawberries',
    'pots',
    'church',
    'bicycles',
    'policeman',
    'blender',
    'spice',
    'doll',
    'stuffed bear',
    'cabin',
    'cookie',
    'pedestrian',
    'soda',
    'decorations',
    'toilet bowl',
    'skate park',
    'sculpture',
    'snowboarder',
    'device',
    'basil',
    'pumpkin',
    'passengers',
    'logs',
    'street lights',
    'kettle',
    'shop',
    'bandana',
    'urinal',
    'benches',
    'sailboat',
    'corn',
    'stars',
    'fans',
    'dessert',
    'napkins',
    'figurine',
    'motorcycles',
    'wristwatch',
    'lip',
    'shirts',
    'barn',
    'ham',
    'ship',
    'cage',
    'traffic lights',
    'island',
    'lamb',
    'bedspread',
    'cream',
    'eggs',
    'sheets',
    'carriage',
    'candles',
    'locomotive',
    'pigeon',
    'dishes',
    'train station',
    'tree branches',
    'artwork',
    'scooter',
    'porch',
    'cones',
    'bus stop',
    'pastry',
    'snowsuit',
    'flower pot',
    'beans',
    'microphone',
    'spices',
    'containers',
    'pillars',
    'steering wheel',
    'tissue',
    'olives',
    'figure',
    'potatoes',
    'fruits',
    'bleachers',
    'silverware',
    'waist',
    'grapes',
    'dishwasher',
    'coffee cup',
    'hedge',
    'giraffes',
    'fish',
    'ski lift',
    'bikes',
    'headphones',
    'staircase',
    'chocolate',
    'stroller',
    'zebras',
    'card',
    'cucumber',
    'cutting board',
    'stickers',
    'placemat',
    'clock tower',
    'dresser',
    'wine bottle',
    'traffic sign',
    'women',
    'computer monitor',
    'passenger',
    'lamp shade',
    'candy',
    'wii controller',
    'skateboarder',
    'magazine',
    'newspaper',
    'mustard',
    'utensils',
    'pipes',
    'cupboard',
    'dugout',
    'drawing',
    'cabinet door',
    'wool',
    'crumbs',
    'cooler',
    'mouse pad',
    'players',
    'stuffed animal',
    'intersection',
    'mud',
    'goat',
    'marker',
    'bedroom',
    'cups',
    'juice',
    'coffee',
    'crane',
    'spinach',
    'toilet seat',
    'cables',
    'zoo',
    'twig',
    'sausage',
    'trailer',
    'trunks',
    'menu',
    'buoy',
    'rose',
    'yard',
    'grape',
    'horses',
    'machine',
    'restaurant',
    'roll',
    'lock',
    'saucer',
    'bacon',
    'cupcake',
    'deck',
    'lemon',
    'sticks',
    'living room',
    'ice',
    'blouse',
    'lawn',
    'dome',
    'dispenser',
    'puddle',
    'ketchup',
    'toppings',
    'rice',
    'parking meter',
    'palm trees',
    'strawberry',
    'bell',
    'antenna',
    'pine trees',
    'elephants',
    'balloon',
    'cords',
    'tree branch',
    'mound',
    'paddle',
    'salad',
    'kites',
    'utensil',
    'crate',
    'sail',
    'soap',
    'towels',
    'driver',
    'entrance',
    'water bottle',
    'cows',
    'jet',
    'sweatshirt',
    'shower',
    'peppers',
    'coffee table',
    'fries',
    'bookshelf',
    'lake',
    'comforter',
    'beer',
    'hook',
    'nightstand',
    'vehicles',
    'magnet',
    'fireplace',
    'icing',
    'power line',
    'hose',
    'egg',
    'fence post',
    'heart',
    'drink',
    'potato',
    'light fixture',
    'umbrellas',
    'shelves',
    'toothbrush',
    'drawers',
    'airport',
    'light bulb',
    'apron',
    'duck',
    'moss',
    'baseball bat',
    'houses',
    'pitcher',
    'oranges',
    'paws',
    'sandal',
    'onions',
    'sandals',
    'bags',
    'sofa',
    'tomatoes',
    'flags',
    'boxes',
    'walls',
    'tires',
    'toy',
    'pond',
    'children',
    'mustache',
    'station',
    'donuts',
    'surfer',
    'apples',
    'hillside',
    'tape',
    'hay',
    'toilet paper',
    'mushroom',
    'crosswalk',
    'lips',
    'telephone pole',
    'mat',
    'boats',
    'mug',
    'baseball',
    'cross',
    'plates',
    'planter',
    'animals',
    'hills',
    'olive',
    'scissors',
    'barrier',
    'tank top',
    'wine glass',
    'suv',
    'topping',
    'batter',
    'stones',
    'mask',
    'american flag',
    'chicken',
    'game',
    'sheet',
    'spectators',
    'drain',
    'taxi',
    'river',
    'carrots',
    'controller',
    'wings',
    'smoke',
    'canopy',
    'tongue',
    'cable',
    'brush',
    'umpire',
    'grill',
    'birds',
    'decoration',
    'burner',
    'papers',
    'tennis ball',
    'power lines',
    'sprinkles',
    'bottles',
    'ladder',
    'couple',
    'display',
    'straw',
    'stop sign',
    'skin',
    'pillows',
    'headboard',
    'fan',
    'spectator',
    'store',
    'earring',
    'headband',
    'microwave',
    'baby',
    'teddy bear',
    'train car',
    'runway',
    'pan',
    'tablecloth',
    'liquid',
    'symbol',
    'propeller',
    'crowd',
    'thumb',
    'bun',
    'pepperoni',
    'bucket',
    'frosting',
    'hot dog',
    'light switch',
    'poster',
    'pen',
    'cockpit',
    'step',
    'dock',
    'painting',
    'curtains',
    'tent',
    'cart',
    'jar',
    'walkway',
    'city',
    'oven',
    'lettuce',
    'pine tree',
    'countertop',
    'cabinets',
    'eye glasses',
    'outfit',
    'log',
    'bathtub',
    'blinds',
    'forest',
    'trash',
    'catcher',
    'steps',
    'fingers',
    'speaker',
    'home plate',
    'monitor',
    'feathers',
    'chairs',
    'chimney',
    'weeds',
    'stove',
    'crust',
    'men',
    'teeth',
    'skier',
    'path',
    'wine',
    'doorway',
    'star',
    'arms',
    'sandwich',
    'vegetable',
    'sun',
    'dish',
    'statue',
    'onion',
    'train tracks',
    'park',
    'parking lot',
    'wristband',
    'necklace',
    'bracelet',
    'vegetables',
    'beard',
    'luggage',
    'purse',
    'graffiti',
    'gate',
    'scarf',
    'stairs',
    'doors',
    'pepper',
    'horns',
    'net',
    'snowboard',
    'can',
    'outlet',
    'pocket',
    'street sign',
    'clothes',
    'computer mouse',
    'suitcase',
    'rug',
    'boots',
    'shore',
    'remote control',
    'candle',
    'jersey',
    'kitchen',
    'chain',
    'fire hydrant',
    'palm tree',
    'skirt',
    'tree trunk',
    'carpet',
    'balcony',
    'gloves',
    'mountains',
    'wetsuit',
    'computer',
    'refrigerator',
    'beak',
    'pavement',
    'stick',
    'label',
    'vest',
    'platform',
    'gravel',
    'bridge',
    'goggles',
    'van',
    'meat',
    'bricks',
    'spoon',
    'ring',
    'sauce',
    'boot',
    'suit',
    'books',
    'carrot',
    'bathroom',
    'rope',
    'bat',
    'pipe',
    'socks',
    'tray',
    'wires',
    'television',
    'words',
    'belt',
    'tiles',
    'tomato',
    'ski',
    'paint',
    'camera',
    'trash can',
    'plants',
    'air',
    'horn',
    'frisbee',
    'couch',
    'room',
    'vehicle',
    'skis',
    'cake',
    'bicycle',
    'sweater',
    'bananas',
    'bread',
    'cone',
    'napkin',
    'apple',
    'spots',
    'guy',
    'cord',
    't-shirt',
    'ocean',
    'knife',
    'fruit',
    'drawer',
    'numbers',
    'orange',
    'broccoli',
    'blanket',
    'stone',
    'sneakers',
    'arrow',
    'keyboard',
    'watch',
    'cell phone',
    'screen',
    'faucet',
    'tower',
    'dress',
    'tag',
    'bear',
    'ears',
    'pot',
    'curtain',
    'cars',
    'toilet',
    'desk',
    'word',
    'buildings',
    'wrist',
    'beach',
    'fork',
    'wire',
    'uniform',
    'laptop',
    'fur',
    'cheese',
    'license plate',
    'mane',
    'lady',
    'donut',
    'branches',
    'sticker',
    'animal',
    'phone',
    'vase',
    'basket',
    'lid',
    'mountain',
    'collar',
    'backpack',
    'paw',
    'pizza',
    'traffic light',
    'towel',
    'tie',
    'sock',
    'container',
    'sink',
    'cat',
    'bed',
    'child',
    'hill',
    'bushes',
    'player',
    'motorcycle',
    'finger',
    'feet',
    'windshield',
    'frame',
    'surfboard',
    'hands',
    'sand',
    'wheels',
    'bike',
    'zebra',
    'ball',
    'eyes',
    'cabinet',
    'skateboard',
    'ceiling',
    'flag',
    'racket',
    'truck',
    'book',
    'cow',
    'rocks',
    'giraffe',
    'branch',
    'banana',
    'glove',
    'street light',
    'sheep',
    'counter',
    'house',
    'cup',
    'seat',
    'dog',
    'paper',
    'elephant',
    'kite',
    'wing',
    'lamp',
    'airplane',
    'coat',
    'plant',
    'horse',
    'trunk',
    'pillow',
    'train',
    'bus',
    'shelf',
    'bowl',
    'letters',
    'food',
    'neck',
    'clock',
    'dirt',
    'bird',
    'box',
    'bench',
    'mirror',
    'picture',
    'field',
    'glasses',
    'flowers',
    'shoes',
    'bush',
    'girl',
    'bottle',
    'cap',
    'boat',
    'mouth',
    'jeans',
    'post',
    'umbrella',
    'legs',
    'foot',
    'street',
    'glass',
    'roof',
    'cloud',
    'logo',
    'tire',
    'boy',
    'rock',
    'snow',
    'helmet',
    'bag',
    'flower',
    'sidewalk',
    'road',
    'shorts',
    'windows',
    'plate',
    'letter',
    'number',
    'clouds',
    'leaf',
    'face',
    'tail',
    'shoe',
    'hat',
    'jacket',
    'arm',
    'floor',
    'chair',
    'nose',
    'wheel',
    'fence',
    'water',
    'door',
    'eye',
    'people',
    'pants',
    'ear',
    'trees',
    'table',
    'leaves',
    'woman',
    'car',
    'leg',
    'hair',
    'grass',
    'hand',
    'pole',
    'head',
    'sign',
    'sky',
    'ground',
    'building',
    'person',
    'wall',
    'tree',
    'shirt',
    'man',
    'window',
]

ATTRS = [
    'immature',
    'uncomfortable',
    'typical',
    'complete',
    'scarce',
    'polar',
    'irregular',
    'polo',
    'unhealthy',
    'fine',
    'chalk',
    'coarse',
    'unhappy',
    'incomplete',
    'abstract',
    'regular',
    'forested',
    'wrist',
    'breaking',
    'hollow',
    'breakable',
    'pastel',
    'urban',
    'quilted',
    'intricate',
    'sealed',
    'park',
    'exterior',
    'soap',
    'strawberry',
    'unpaved',
    'soda',
    'packaged',
    'inflatable',
    'ornamental',
    'fluorescent',
    'pepper',
    'abundant',
    'opaque',
    'ugly',
    'garbage',
    'powerful',
    'elongated',
    'industrial',
    'chubby',
    'rugged',
    'sculpted',
    'burning',
    'patched',
    'gas',
    'handmade',
    'clumped',
    'railroad',
    'simple',
    'translucent',
    'mature',
    'tomato',
    'crisp',
    'boiled',
    'recessed',
    'oversized',
    'vinyl',
    'spinning',
    'office',
    'melting',
    'silk',
    'discolored',
    'corded',
    'formal',
    'vacant',
    'wooded',
    'sturdy',
    'vibrant',
    'misty',
    'beer',
    'groomed',
    'glossy',
    'scrambled',
    'wii',
    'vast',
    'sleepy',
    'rainy',
    'birthday',
    'polished',
    'funny',
    'crashing',
    'powdered',
    'lower',
    'winding',
    'calico',
    'banana',
    'angry',
    'inflated',
    'oriental',
    'folding',
    'crusty',
    'rimmed',
    'grated',
    'curvy',
    'telephone',
    'unoccupied',
    'curious',
    'rotten',
    'uneven',
    'fire',
    'rustic',
    'trash',
    'artificial',
    'spiral',
    'crumbled',
    'dangling',
    'cordless',
    'wedding',
    'french',
    'support',
    'performing trick',
    'comfortable',
    'foreign',
    'knotted',
    'upper',
    'coffee',
    'lace',
    'ridged',
    'connected',
    'ivory',
    'christmas',
    'professional',
    'creamy',
    'analog',
    'jagged',
    'oblong',
    'ruffled',
    'iced',
    'upholstered',
    'gloomy',
    'toilet',
    'unlit',
    'browned',
    'cylindrical',
    'greasy',
    'abandoned',
    'capital',
    'feathered',
    'dull',
    'tropical',
    'twisted',
    'crooked',
    'wine',
    'fenced',
    'sprinkled',
    'tangled',
    'stormy',
    'blank',
    'tasty',
    'hitting',
    'deciduous',
    'frozen',
    'license',
    'cushioned',
    'torn',
    'crowded',
    'tail',
    'beaded',
    'suspended',
    'sloped',
    'sweet',
    'miniature',
    'domed',
    'pizza',
    'paneled',
    'homemade',
    'seasoned',
    'diamond',
    'crystal',
    'angled',
    'weathered',
    'shadowed',
    'juicy',
    'pine',
    'barbed',
    'safety',
    'shingled',
    'roasted',
    'sad',
    'packed',
    'rippling',
    'vanilla',
    'eaten',
    'shut',
    'looking up',
    'mowed',
    'disposable',
    'portable',
    'tabby',
    'strong',
    'pulled back',
    'wrinkly',
    'muscular',
    'edged',
    'directional',
    'tight',
    'partly cloudy',
    'unpeeled',
    'carved',
    'damaged',
    'braided',
    'steamed',
    'gloved',
    'spraying',
    'commercial',
    'steep',
    'bamboo',
    'perched',
    'shaved',
    'uncooked',
    'spiky',
    'wool',
    'american',
    'assorted',
    'sunlit',
    'chipped',
    'blooming',
    'real',
    'peeled',
    'alert',
    'neat',
    'public',
    'drawn',
    'cobblestone',
    'massive',
    'wired',
    'mixed',
    'bronze',
    'halved',
    'jeans',
    'tin',
    'dense',
    'adidas',
    'military',
    'peeling',
    'diced',
    'loose',
    'caucasian',
    'speckled',
    'batting',
    'manicured',
    'indoors',
    'winter',
    'padded',
    'half full',
    'shaped',
    'laughing',
    'sheer',
    'foamy',
    'unripe',
    'cheese',
    'blowing',
    'copper',
    'palm',
    'styrofoam',
    'elevated',
    'chinese',
    'brass',
    'textured',
    'spread',
    'brunette',
    'warm',
    'cluttered',
    'crispy',
    'elderly',
    'bunched',
    'clay',
    'made',
    'power',
    'athletic',
    'lighted',
    'woven',
    'collared',
    'traffic',
    'dotted',
    'mesh',
    'raw',
    'crumpled',
    'flowered',
    'dusty',
    'shaded',
    'tilted',
    'plush',
    'ocean',
    'sliding',
    'apple',
    'looking down',
    'overgrown',
    'wireless',
    'designed',
    'reading',
    'giant',
    'barren',
    'stained',
    'scattered',
    'new',
    'shaggy',
    'foggy',
    'rippled',
    'cloth',
    'squatting',
    'protective',
    'electronic',
    'carpeted',
    'fat',
    'waving',
    'cotton',
    'octagonal',
    'shallow',
    'sparse',
    'hard',
    'docked',
    'navy',
    'crouched',
    'shredded',
    'computer',
    'horizontal',
    'vintage',
    'old fashioned',
    'cooking',
    'baked',
    'fancy',
    'transparent',
    'roman',
    'cracked',
    'snow',
    'heavy',
    'balding',
    'outdoor',
    'teal',
    'gravel',
    'glowing',
    'faded',
    'slanted',
    'staring',
    'street',
    'antique',
    'mounted',
    'soccer',
    'still',
    'busy',
    'snowboarding',
    'murky',
    'used',
    'kneeling',
    'kitchen',
    'turned',
    'modern',
    'granite',
    'rainbow colored',
    'fallen',
    'pretty',
    'sleeveless',
    'deep',
    'bathroom',
    'swimming',
    'messy',
    'attached',
    'wrapped',
    'rolled',
    'rounded',
    'grilled',
    'female',
    'straw',
    'tied',
    'vertical',
    'knit',
    'toy',
    'wispy',
    'fake',
    'choppy',
    'toasted',
    'neon',
    'soft',
    'patchy',
    'bending',
    'digital',
    'skating',
    'trimmed',
    'aluminum',
    'illuminated',
    'written',
    'frosted',
    'crouching',
    'printed',
    'healthy',
    'plain',
    'barefoot',
    'delicious',
    'reflected',
    'having meeting',
    'drinking',
    'displayed',
    'lined',
    'rough',
    'outstretched',
    'floppy',
    'sharp',
    'swinging',
    'asian',
    'decorated',
    'pale',
    'muddy',
    'overhead',
    'potted',
    'outdoors',
    'fuzzy',
    'crossed',
    'burnt',
    'asphalt',
    'filled',
    'floating',
    'shining',
    'tinted',
    'wild',
    'ornate',
    'fried',
    'rock',
    'marble',
    'male',
    'double decker',
    'glazed',
    'pointing',
    'water',
    'ski',
    'upside down',
    'posing',
    'shirtless',
    'splashing',
    'chopped',
    'curled',
    'wavy',
    'nike',
    'khaki',
    'stuffed',
    'hairy',
    'dark colored',
    'adult',
    'wrinkled',
    'resting',
    'sleeping',
    'bushy',
    'dried',
    'sunny',
    'hardwood',
    'triangular',
    'wicker',
    'straight',
    'grouped',
    'denim',
    'narrow',
    'evergreen',
    'low',
    'smooth',
    'puffy',
    'broken',
    'wire',
    'chrome',
    'talking',
    'rubber',
    'skateboarding',
    'piled',
    'melted',
    'black and white',
    'iron',
    'floral',
    'bald',
    'reflective',
    'porcelain',
    'cardboard',
    'off',
    'dark blue',
    'lush',
    'raised',
    'riding',
    'maroon',
    'jumping',
    'driving',
    'curly',
    'patterned',
    'skinny',
    'rocky',
    'light colored',
    'bent',
    'worn',
    'baby',
    'huge',
    'cream colored',
    'chocolate',
    'fresh',
    'tiny',
    'hazy',
    'high',
    'checkered',
    'dark brown',
    'cloudless',
    'light blue',
    'down',
    'short sleeved',
    'rusty',
    'long sleeved',
    'furry',
    'ripe',
    'stainless steel',
    'waiting',
    'ceramic',
    'running',
    'wide',
    'cut',
    'steel',
    'overcast',
    'chain-link',
    'arched',
    'sandy',
    'folded',
    'up',
    'decorative',
    'beautiful',
    'light brown',
    'skiing',
    'curved',
    'leafless',
    'flat',
    'grazing',
    'blurry',
    'lit',
    'framed',
    'paper',
    'covered',
    'full',
    'stacked',
    'grassy',
    'cooked',
    'electric',
    'plaid',
    'fluffy',
    'clean',
    'paved',
    'snowy',
    'surfing',
    'lying',
    'pointy',
    'eating',
    'painted',
    'leather',
    'tiled',
    'dry',
    'calm',
    'rectangular',
    'beige',
    'thick',
    'playing',
    'leafy',
    'sliced',
    'little',
    'tennis',
    'square',
    'thin',
    'on',
    'shiny',
    'flying',
    'dirty',
    'light',
    'smiling',
    'stone',
    'gold',
    'wet',
    'bright',
    'happy',
    'baseball',
    'closed',
    'old',
    'young',
    'empty',
    'bare',
    'blond',
    'concrete',
    'hanging',
    'cloudy',
    'colorful',
    'striped',
    'purple',
    'tan',
    'brick',
    'walking',
    'plastic',
    'parked',
    'short',
    'sitting',
    'open',
    'glass',
    'round',
    'clear',
    'standing',
    'pink',
    'silver',
    'dark',
    'long',
    'orange',
    'metal',
    'tall',
    'yellow',
    'wood',
    'small',
    'large',
    'gray',
    'red',
    'brown',
    'blue',
    'green',
    'black',
    'white',
]